from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QScrollBar, QTableWidget

class ScrollBar(QScrollBar):
    def __init__(self):
        super().__init__()
        # setMouseTracking - свойство поддерживает отслеживание мыши для виджета.
        self.setMouseTracking(True)
        # VerticalScrollBarPolicy - свойство содержит политику вертикальной полосы прокрутки
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
    # enterEvent - обработчик событий. Событие отправляется в виджет, когда курсор мыши входит в виджет.
    def enterEvent(self, event):
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.setStyleSheet("""
        QScrollBar:vertical {              
            border: none;
            background: white;
            width: 7px;               
            margin: 0px 0px 0px 0px;
        }
        QScrollBar::handle:vertical {
            background: #32CC99;
            min-height: 0px;
        }
        QScrollBar::add-line:vertical {
            background: #32CC99;
            height: 0px;
            subcontrol-position: bottom;
            subcontrol-origin: margin;
        }
        QScrollBar::sub-line:vertical {
            background: #32CC99;
            height: 0 px;
            subcontrol-position: top;
            subcontrol-origin: margin;
        }      
                    QScrollBar:horizontal {              
            border: none;
            background: white;
            height: 7px;               
            margin: 0px 0px 0px 0px;
        }
        QScrollBar::handle:horizontal {
            background: #32CC99;
            min-width: 0px;
        }
        QScrollBar::add-line:horizontal {
            background: #32CC99;
            width: 0px;
            subcontrol-position: right;
            subcontrol-origin: margin;
        }
        QScrollBar::sub-line:horizontal {
            background: #32CC99;
            width: 0 px;
            subcontrol-position: left;
            subcontrol-origin: margin;
        }
    """)
    def leaveEvent(self, event):
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)


class MyTableWidget(QTableWidget, ScrollBar):
    def __init__(self, parent):
        super(MyTableWidget, self).__init__()
        self.setParent(parent)
        self.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 718)
        MainWindow.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(189, 189, 189);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.start_time_delivery = QtWidgets.QLabel(self.groupBox)
        self.start_time_delivery.setMinimumSize(QtCore.QSize(50, 25))
        self.start_time_delivery.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_time_delivery.setFont(font)
        self.start_time_delivery.setText("")
        self.start_time_delivery.setObjectName("start_time_delivery")
        self.horizontalLayout_2.addWidget(self.start_time_delivery)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.start_duration = QtWidgets.QLabel(self.groupBox)
        self.start_duration.setMinimumSize(QtCore.QSize(50, 25))
        self.start_duration.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_duration.setFont(font)
        self.start_duration.setText("")
        self.start_duration.setObjectName("start_duration")
        self.horizontalLayout_10.addWidget(self.start_duration)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.start_requestion = QtWidgets.QLabel(self.groupBox)
        self.start_requestion.setMinimumSize(QtCore.QSize(50, 25))
        self.start_requestion.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_requestion.setFont(font)
        self.start_requestion.setText("")
        self.start_requestion.setObjectName("start_requestion")
        self.horizontalLayout_8.addWidget(self.start_requestion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.start_risk = QtWidgets.QLabel(self.groupBox)
        self.start_risk.setMinimumSize(QtCore.QSize(50, 25))
        self.start_risk.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_risk.setFont(font)
        self.start_risk.setText("")
        self.start_risk.setObjectName("start_risk")
        self.horizontalLayout_11.addWidget(self.start_risk)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.start_time_model = QtWidgets.QLabel(self.groupBox)
        self.start_time_model.setMinimumSize(QtCore.QSize(50, 25))
        self.start_time_model.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_time_model.setFont(font)
        self.start_time_model.setText("")
        self.start_time_model.setObjectName("start_time_model")
        self.horizontalLayout_3.addWidget(self.start_time_model)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.solution = QtWidgets.QPushButton(self.groupBox)
        self.solution.setMinimumSize(QtCore.QSize(125, 35))
        self.solution.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solution.setFont(font)
        self.solution.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.solution.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.solution.setObjectName("solution")
        self.gridLayout.addWidget(self.solution, 1, 0, 1, 1)
        self.button_set_params = QtWidgets.QPushButton(self.groupBox)
        self.button_set_params.setMinimumSize(QtCore.QSize(125, 35))
        self.button_set_params.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_set_params.setFont(font)
        self.button_set_params.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_set_params.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_set_params.setObjectName("button_set_params")
        self.gridLayout.addWidget(self.button_set_params, 0, 0, 1, 1)
        self.button_save = QtWidgets.QPushButton(self.groupBox)
        self.button_save.setMinimumSize(QtCore.QSize(125, 35))
        self.button_save.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_save.setFont(font)
        self.button_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save.setObjectName("button_save")
        self.gridLayout.addWidget(self.button_save, 0, 1, 1, 1)
        self.button_load = QtWidgets.QPushButton(self.groupBox)
        self.button_load.setMinimumSize(QtCore.QSize(125, 35))
        self.button_load.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_load.setFont(font)
        self.button_load.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_load.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_load.setObjectName("button_load")
        self.gridLayout.addWidget(self.button_load, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.result_b_ui = QtWidgets.QLabel(self.groupBox_2)
        self.result_b_ui.setMinimumSize(QtCore.QSize(50, 25))
        self.result_b_ui.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_b_ui.setFont(font)
        self.result_b_ui.setText("")
        self.result_b_ui.setObjectName("result_b_ui")
        self.horizontalLayout_15.addWidget(self.result_b_ui)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.result_m_ui = QtWidgets.QLabel(self.groupBox_2)
        self.result_m_ui.setMinimumSize(QtCore.QSize(50, 25))
        self.result_m_ui.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_m_ui.setFont(font)
        self.result_m_ui.setText("")
        self.result_m_ui.setObjectName("result_m_ui")
        self.horizontalLayout_16.addWidget(self.result_m_ui)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.set_params_graph_end = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.set_params_graph_end.setFont(font)
        self.set_params_graph_end.setObjectName("set_params_graph_end")
        self.horizontalLayout_23.addWidget(self.set_params_graph_end)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.tableWidget = MyTableWidget(self.groupBox_2)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_graph = QtWidgets.QVBoxLayout()
        self.verticalLayout_graph.setSpacing(0)
        self.verticalLayout_graph.setObjectName("verticalLayout_graph")
        self.verticalLayout_6.addLayout(self.verticalLayout_graph)
        self.verticalLayout_4.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.save_raw_data = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_raw_data.setFont(font)
        self.save_raw_data.setObjectName("save_raw_data")
        self.load_raw_data = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_raw_data.setFont(font)
        self.load_raw_data.setObjectName("load_raw_data")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem(str('Время')))
        self.tableWidget.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem(str('Заказ')))
        self.set_params_graph_end.setDisabled(True)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Входные параметры:"))
        self.label_2.setText(_translate("MainWindow", "Время доставки (Δt):"))
        self.label_10.setText(_translate("MainWindow", "Интервал между проверками уровня запаса t(пр):"))
        self.label_9.setText(_translate("MainWindow", "Средний спрос (W):"))
        self.label_11.setText(_translate("MainWindow", "Коэффициент риска (p):"))
        self.label_6.setText(_translate("MainWindow", "Время моделирования T(мод):"))
        self.solution.setText(_translate("MainWindow", "Найти решение"))
        self.button_set_params.setText(_translate("MainWindow", "Задать параметры"))
        self.button_save.setText(_translate("MainWindow", "Сохранить"))
        self.button_load.setText(_translate("MainWindow", "Загрузить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выходные параметры:"))
        self.label_13.setText(_translate("MainWindow", "Размер страхового запаса (b):"))
        self.label_14.setText(_translate("MainWindow", "Фиксированный уровень запаса (M):"))
        self.set_params_graph_end.setText(_translate("MainWindow", "Настройка графика"))
        self.save_raw_data.setText(_translate("MainWindow", "Сохранить"))
        self.load_raw_data.setText(_translate("MainWindow", "Загрузить"))